[build]
target = "index.html"
dist = "../../dist/admin"
public_url = "/admin/"

[serve]
port = 8081
address = "0.0.0.0"

[watch]
watch = ["src"]

[[proxy]]
rewrite = "/api/"
backend = "http://localhost:3000/api/"
