#!/usr/bin/env bash
# Novice-friendly install: generate secrets (incl. free host port) and start Podman Compose.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS="$ROOT/data/secrets.env"
cd "$ROOT"

if ! command -v podman >/dev/null 2>&1; then
    echo "error: podman is required" >&2
    exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "error: openssl is required to generate secrets" >&2
    exit 1
fi

mkdir -p "$ROOT/data"

port_is_free() {
    local p="$1"
    if command -v ss >/dev/null 2>&1; then
        ! ss -tlnH "sport = :$p" 2>/dev/null | grep -q .
    else
        # bash /dev/tcp: success means something accepted the connection (port in use)
        ! (echo >/dev/tcp/127.0.0.1/"$p") 2>/dev/null
    fi
}

pick_host_port() {
    local p candidates=(3000 8080 9090 3100 8888 18080)
    for p in "${candidates[@]}"; do
        if port_is_free "$p"; then
            echo "$p"
            return 0
        fi
    done
    local i
    for i in $(seq 1 40); do
        p=$((9100 + RANDOM % 20000))
        if port_is_free "$p"; then
            echo "$p"
            return 0
        fi
    done
    echo "error: could not find a free host port" >&2
    return 1
}

if [[ ! -f "$SECRETS" ]]; then
    echo "Generating $SECRETS ..."
    SURREALDB_PASSWORD="$(openssl rand -base64 32 | tr -d '\n')"
    ENCRYPTION_KEY="$(openssl rand -base64 32 | tr -d '\n')"
    HOST_PORT="$(pick_host_port)"
    echo "Selected free host port: ${HOST_PORT} (bound to 127.0.0.1 only)"
    if [[ -t 0 ]]; then
        read -rp "Public site URL [http://127.0.0.1:${HOST_PORT}]: " REDIRECT_BASE_URL || true
    else
        REDIRECT_BASE_URL=""
    fi
    REDIRECT_BASE_URL="${REDIRECT_BASE_URL:-http://127.0.0.1:${HOST_PORT}}"
    umask 077
    cat > "$SECRETS" <<EOF
# Generated by scripts/install.sh — do not commit
SURREALDB_USER=root
SURREALDB_PASSWORD=${SURREALDB_PASSWORD}
SURREALDB_NS=scuffed_crew
SURREALDB_DB=main
ENCRYPTION_KEY=${ENCRYPTION_KEY}
ENCRYPTION_KEY_VERSION=1
HOST_PORT=${HOST_PORT}
REDIRECT_BASE_URL=${REDIRECT_BASE_URL}
ALLOWED_ORIGINS=${REDIRECT_BASE_URL}
RUST_LOG=info
EOF
    chmod 600 "$SECRETS"
    echo "Wrote secrets (mode 600). Database password is not shown again."
    echo "  file: $SECRETS"
else
    echo "Using existing $SECRETS"
    # shellcheck disable=SC1090
    set -a
    # shellcheck source=/dev/null
    source "$SECRETS"
    set +a
    HOST_PORT="${HOST_PORT:-3000}"
    REDIRECT_BASE_URL="${REDIRECT_BASE_URL:-http://127.0.0.1:${HOST_PORT}}"
fi

if podman compose version >/dev/null 2>&1; then
    COMPOSE=(podman compose)
elif command -v podman-compose >/dev/null 2>&1; then
    COMPOSE=(podman-compose)
else
    echo "error: need 'podman compose' or 'podman-compose'" >&2
    exit 1
fi

# Prefer prebuilt image from GHCR (published by .github/workflows/publish-image.yml).
SITE_SERVER_IMAGE="${SITE_SERVER_IMAGE:-ghcr.io/frozentear/scuffed-crew:main}"
export SITE_SERVER_IMAGE
if ! grep -q '^SITE_SERVER_IMAGE=' "$SECRETS" 2>/dev/null; then
    echo "SITE_SERVER_IMAGE=${SITE_SERVER_IMAGE}" >> "$SECRETS"
fi

BUILD_FROM_SOURCE="${BUILD_FROM_SOURCE:-0}"

if [[ "$BUILD_FROM_SOURCE" == "1" ]]; then
    echo "BUILD_FROM_SOURCE=1 — compiling site-server on this machine (slow)..."
    "${COMPOSE[@]}" --env-file "$SECRETS" up --build -d
else
    echo "Pulling prebuilt ${SITE_SERVER_IMAGE} (no local compile)..."
    if podman pull "${SITE_SERVER_IMAGE}"; then
        "${COMPOSE[@]}" --env-file "$SECRETS" up -d
    else
        echo
        echo "Pull failed — falling back to local --build (can take a long time)."
        echo "After the first successful GHCR publish, re-run without BUILD_FROM_SOURCE."
        echo "  Private package?  podman login ghcr.io"
        echo "  Or force build:   BUILD_FROM_SOURCE=1 $0"
        "${COMPOSE[@]}" --env-file "$SECRETS" up --build -d
    fi
fi

echo
echo "Stack starting on 127.0.0.1:${HOST_PORT} (HOST_PORT is persisted in secrets)."
echo "Image: ${SITE_SERVER_IMAGE}"
echo "Next steps:"
echo "  1. If public: point Caddy at 127.0.0.1:${HOST_PORT} (see docs/deploy.md)"
echo "  2. Open ${REDIRECT_BASE_URL} and create the admin account (first boot)"
echo "  3. Later updates: ./scripts/update.sh  (git pull + image pull, no compile)"
echo "  4. Infra secrets file: ${SECRETS}"
echo "Optional relay: ${COMPOSE[*]} --env-file ${SECRETS} --profile relay up -d"
