mod announcements;
mod applications;
mod audit_log;
mod dashboard;
mod games;
mod matches;
mod members;
mod schedule;
mod settings;
mod teams;
mod tournaments;

pub use announcements::AnnouncementsPage;
pub use applications::ApplicationsPage;
pub use audit_log::AuditLogPage;
pub use dashboard::DashboardPage;
pub use games::GamesPage;
pub use matches::MatchesPage;
pub use members::MembersPage;
pub use schedule::SchedulePage;
pub use settings::SettingsPage;
pub use teams::TeamsPage;
pub use tournaments::TournamentsPage;
